---
apiVersion: v1
kind: Namespace
metadata:
  name: lab1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003-nfs
  namespace: lab1
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: pv0003-nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfsshare/pv0003
    server: 192.168.1.195
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv0003-nfs
  namespace: lab1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pv0003-nfs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: lab1
  labels:
    app: hello-world
spec:
  selector:
    matchLabels:
      run: load-balancer-example
  replicas: 1
  template:
    metadata:
      labels:
        run: load-balancer-example
    spec:
      volumes:
        - name: helloworld-pv-storage
          persistentVolumeClaim:
            claimName: pv0003-nfs
      containers:
        - name: hello-world
          image: gcr.io/google-samples/node-hello:1.0
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: "/mnt"
              name: helloworld-pv-storage

