apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv0003-nfs
  namespace: lab1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pv0003-nfs
  resources:
    requests:
      storage: 5Gi
