---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: lab1
  labels:
    app: hello-world
spec:
  selector:
    matchLabels:
      run: load-balancer-example
  replicas: 1
  template:
    metadata:
      labels:
        run: load-balancer-example
    spec:
      volumes:
        - name: helloworld-pv-storage
          persistentVolumeClaim:
            claimName: pv0003-nfs
      containers:
        - name: hello-world
          image: gcr.io/google-samples/node-hello:1.0
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: "/mnt"
              name: helloworld-pv-storage
